'use client';

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Locale = 'ko' | 'en' | 'ja' | 'fr';

export const LANGUAGES: Array<{ code: Locale; label: string; short: string }> = [
  { code: 'ko', label: '한국어', short: 'KO' },
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'ja', label: '日本語', short: 'JA' },
  { code: 'fr', label: 'Français', short: 'FR' },
];

const dictionaries: Record<Locale, Record<string, string>> = {
  ko: {
    'nav.home': '홈',
    'nav.webtoons': '무제한 웹툰',
    'nav.novels': '무제한 소설',
    'nav.gallery': '화보',
    'nav.community': '게시판',
    'nav.chat': '캐릭터 채팅',
    'nav.shortAnime': '숏폼 애니',
    'nav.games': '게임',
    'nav.attendance': '출석',
    'nav.new': '신작',
    'nav.fullEdition': '완전판',
    'common.menu': '메뉴',
    'common.closeMenu': '메뉴 닫기',
    'common.openMenu': '메뉴 열기',
    'common.search': '검색',
    'common.more': '더보기 +',
    'common.loginJoin': '로그인 / 회원가입',
    'common.language': '언어',
    'common.themeLight': '라이트 모드',
    'common.themeDark': '다크 모드',
    'common.displayAdult': '성인 작품 표시',
    'common.showAdult': '성인 작품 표시',
    'common.hideAdult': '성인 작품 숨기기',
    'common.checkIn': '출석 체크',
    'common.comingSoonShortAnime': '숏폼 애니는 준비중입니다.',
    'recent.title': '최근 본 작품',
    'recent.empty': '최근 감상한 작품이 없습니다.',
    'recent.episode': '{episode}화까지 감상',
    'home.latest': '최신 작품',
    'home.recentWebtoons': '최근에 본 웹툰',
    'home.noRecentWebtoons': '최근 감상한 웹툰이 없습니다.',
    'home.recommendReady': '오늘의 추천 웹툰이 준비중입니다.',
    'home.recommendSub': '매일 새로운 재미, ARATA COMICS에서 만나보세요.',
    'novel.founder': 'ARATA 창립회원 모집',
    'novel.priceLine': '첫 달 990원 | 연간 결제 시 월 2,800원',
    'novel.priceSub': '월결제 시 월 3,400원. 부담없는 금액으로 모든 콘텐츠를 즐기세요.',
    'novel.start': '지금 시작하기',
    'novel.popular': '인기 소설',
    'novel.popularSub': '매일 업데이트되는 다양한 장르의 소설을 만나보세요.',
    'novel.searchPlaceholder': '소설명으로 검색',
    'category.all': '전체',
    'category.fantasy': '판타지',
    'category.martial': '무협',
    'category.romance': '로맨스',
    'category.modern': '현대물',
    'category.lightNovel': '라이트노벨',
    'category.realtime': '실시간',
    'category.action': '액션',
    'category.drama': '드라마',
    'category.school': '학원',
    'category.comedy': '코미디',
    'category.thriller': '스릴러',
    'category.sports': '스포츠',
    'category.daily': '일상',
    'option.freeAll': '완전무료',
    'option.firstFree': '1화 무료',
    'option.webtoon': '웹툰',
    'option.comics': '코믹스',
    'option.color': '컬러만화',
    'option.blackWhite': '흑백만화',
    'option.male': '남성향',
    'option.female': '여성향',
    'list.searchPlaceholder': '작품명, 작가명, 태그로 검색해보세요',
    'list.dateSort': '날짜순',
    'list.likes': '좋아요 {count}',
    'list.views': '조회 {count}',
    'list.defaultSynopsis': 'ARATA에서 연재 중인 웹툰입니다.',
    'list.noTitle': '제목 없음',
    'list.empty': '표시할 작품이 없습니다.',
    'chat.searchPlaceholder': '캐릭터, 작품, 작가 검색',
    'chat.event': '이벤트',
    'chat.subscriptionSale': '아라챗 정액제 50% 할인',
    'chat.ranking': '실시간 캐릭터 랭킹',
    'chat.viewAll': '전체보기',
    'chat.home': '채팅 홈',
    'chat.explore': '탐색',
    'chat.myChat': '내 채팅',
    'chat.favorites': '즐겨찾기',
    'chat.settings': '설정',
    'chat.popularCharacters': '인기 캐릭터',
    'chat.newScenario': '신규 시나리오',
    'chat.noChatTitles': '채팅 가능한 작품이 없습니다.',
    'chat.moreTitles': '작품 더보기',
    'chat.notice': '공지',
    'chat.openNotice': 'ARATA CHAT 오픈! 구독하면 모든 캐릭터와 무제한 대화',
    'chat.noResults': '검색 결과가 없습니다.',
  },
  en: {
    'nav.home': 'Home',
    'nav.webtoons': 'Unlimited Webtoons',
    'nav.novels': 'Unlimited Novels',
    'nav.gallery': 'Gallery',
    'nav.community': 'Board',
    'nav.chat': 'Character Chat',
    'nav.shortAnime': 'Short Anime',
    'nav.games': 'Games',
    'nav.attendance': 'Check-in',
    'nav.new': 'New',
    'nav.fullEdition': 'Full Edition',
    'common.menu': 'Menu',
    'common.closeMenu': 'Close menu',
    'common.openMenu': 'Open menu',
    'common.search': 'Search',
    'common.more': 'More +',
    'common.loginJoin': 'Log in / Sign up',
    'common.language': 'Language',
    'common.themeLight': 'Light mode',
    'common.themeDark': 'Dark mode',
    'common.displayAdult': 'Show adult titles',
    'common.showAdult': 'Show adult titles',
    'common.hideAdult': 'Hide adult titles',
    'common.checkIn': 'Check-in',
    'common.comingSoonShortAnime': 'Short anime is coming soon.',
    'recent.title': 'Recently Viewed',
    'recent.empty': 'No recently viewed titles.',
    'recent.episode': 'Read through episode {episode}',
    'home.latest': 'Latest Works',
    'home.recentWebtoons': 'Recently Viewed Webtoons',
    'home.noRecentWebtoons': 'No recently viewed webtoons.',
    'home.recommendReady': 'Today’s recommendation is coming soon.',
    'home.recommendSub': 'Fresh stories every day on ARATA COMICS.',
    'novel.founder': 'ARATA Founding Member Offer',
    'novel.priceLine': 'First month 990 KRW | Annual plan 2,800 KRW/month',
    'novel.priceSub': 'Monthly plan is 3,400 KRW. Enjoy every title at an easy price.',
    'novel.start': 'Start now',
    'novel.popular': 'Popular Novels',
    'novel.popularSub': 'Meet novels across many genres, updated daily.',
    'novel.searchPlaceholder': 'Search by novel title',
    'category.all': 'All',
    'category.fantasy': 'Fantasy',
    'category.martial': 'Martial Arts',
    'category.romance': 'Romance',
    'category.modern': 'Modern',
    'category.lightNovel': 'Light Novel',
    'category.realtime': 'Real-time',
    'category.action': 'Action',
    'category.drama': 'Drama',
    'category.school': 'School',
    'category.comedy': 'Comedy',
    'category.thriller': 'Thriller',
    'category.sports': 'Sports',
    'category.daily': 'Slice of Life',
    'option.freeAll': 'Free',
    'option.firstFree': 'Episode 1 Free',
    'option.webtoon': 'Webtoon',
    'option.comics': 'Comics',
    'option.color': 'Full Color',
    'option.blackWhite': 'Black & White',
    'option.male': 'For Men',
    'option.female': 'For Women',
    'list.searchPlaceholder': 'Search by title, creator, or tag',
    'list.dateSort': 'Newest',
    'list.likes': 'Likes {count}',
    'list.views': 'Views {count}',
    'list.defaultSynopsis': 'Now serializing on ARATA.',
    'list.noTitle': 'Untitled',
    'list.empty': 'No titles to show.',
    'chat.searchPlaceholder': 'Search characters, titles, creators',
    'chat.event': 'Event',
    'chat.subscriptionSale': 'Character Chat plan 50% off',
    'chat.ranking': 'Live Character Ranking',
    'chat.viewAll': 'View all',
    'chat.home': 'Chat Home',
    'chat.explore': 'Explore',
    'chat.myChat': 'My Chats',
    'chat.favorites': 'Favorites',
    'chat.settings': 'Settings',
    'chat.popularCharacters': 'Popular Characters',
    'chat.newScenario': 'New Scenario',
    'chat.noChatTitles': 'No titles available for chat.',
    'chat.moreTitles': 'More titles',
    'chat.notice': 'Notice',
    'chat.openNotice': 'ARATA CHAT is open. Subscribe to chat with every character.',
    'chat.noResults': 'No results found.',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.webtoons': 'ウェブトゥーン',
    'nav.novels': '小説',
    'nav.gallery': 'ギャラリー',
    'nav.community': '掲示板',
    'nav.chat': 'キャラチャット',
    'nav.shortAnime': 'ショートアニメ',
    'nav.games': 'ゲーム',
    'nav.attendance': '出席',
    'nav.new': '新作',
    'nav.fullEdition': '完全版',
    'common.menu': 'メニュー',
    'common.closeMenu': 'メニューを閉じる',
    'common.openMenu': 'メニューを開く',
    'common.search': '検索',
    'common.more': 'もっと見る +',
    'common.loginJoin': 'ログイン / 会員登録',
    'common.language': '言語',
    'common.themeLight': 'ライトモード',
    'common.themeDark': 'ダークモード',
    'common.displayAdult': '成人向け作品を表示',
    'common.showAdult': '成人向け作品を表示',
    'common.hideAdult': '成人向け作品を非表示',
    'common.checkIn': '出席チェック',
    'common.comingSoonShortAnime': 'ショートアニメは準備中です。',
    'recent.title': '最近見た作品',
    'recent.empty': '最近見た作品はありません。',
    'recent.episode': '{episode}話まで閲覧',
    'home.latest': '最新作品',
    'home.recentWebtoons': '最近見たウェブトゥーン',
    'home.noRecentWebtoons': '最近見たウェブトゥーンはありません。',
    'home.recommendReady': '今日のおすすめは準備中です。',
    'home.recommendSub': '毎日新しい楽しさをARATA COMICSで。',
    'novel.founder': 'ARATA創立会員募集',
    'novel.priceLine': '初月990ウォン | 年間決済で月2,800ウォン',
    'novel.priceSub': '月額は3,400ウォン。手軽な価格で全コンテンツを楽しめます。',
    'novel.start': '今すぐ始める',
    'novel.popular': '人気小説',
    'novel.popularSub': '毎日更新される多彩なジャンルの小説をお楽しみください。',
    'novel.searchPlaceholder': '小説名で検索',
    'category.all': 'すべて',
    'category.fantasy': 'ファンタジー',
    'category.martial': '武侠',
    'category.romance': 'ロマンス',
    'category.modern': '現代',
    'category.lightNovel': 'ライトノベル',
    'category.realtime': 'リアルタイム',
    'category.action': 'アクション',
    'category.drama': 'ドラマ',
    'category.school': '学園',
    'category.comedy': 'コメディ',
    'category.thriller': 'スリラー',
    'category.sports': 'スポーツ',
    'category.daily': '日常',
    'option.freeAll': '完全無料',
    'option.firstFree': '1話無料',
    'option.webtoon': 'ウェブトゥーン',
    'option.comics': 'コミックス',
    'option.color': 'カラー漫画',
    'option.blackWhite': '白黒漫画',
    'option.male': '男性向け',
    'option.female': '女性向け',
    'list.searchPlaceholder': '作品名、作者名、タグで検索',
    'list.dateSort': '新着順',
    'list.likes': 'いいね {count}',
    'list.views': '閲覧 {count}',
    'list.defaultSynopsis': 'ARATAで連載中のウェブトゥーンです。',
    'list.noTitle': 'タイトルなし',
    'list.empty': '表示できる作品がありません。',
    'chat.searchPlaceholder': 'キャラクター、作品、作者を検索',
    'chat.event': 'イベント',
    'chat.subscriptionSale': 'キャラクターチャット定額制50%割引',
    'chat.ranking': 'リアルタイムキャラクターランキング',
    'chat.viewAll': 'すべて見る',
    'chat.home': 'チャットホーム',
    'chat.explore': '探索',
    'chat.myChat': 'マイチャット',
    'chat.favorites': 'お気に入り',
    'chat.settings': '設定',
    'chat.popularCharacters': '人気キャラクター',
    'chat.newScenario': '新規シナリオ',
    'chat.noChatTitles': 'チャット可能な作品はありません。',
    'chat.moreTitles': '作品をもっと見る',
    'chat.notice': 'お知らせ',
    'chat.openNotice': 'ARATA CHAT公開。登録すると全キャラクターとチャットできます。',
    'chat.noResults': '検索結果がありません。',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.webtoons': 'Webtoons illimités',
    'nav.novels': 'Romans illimités',
    'nav.gallery': 'Galerie',
    'nav.community': 'Forum',
    'nav.chat': 'Chat personnages',
    'nav.shortAnime': 'Anime court',
    'nav.games': 'Jeux',
    'nav.attendance': 'Présence',
    'nav.new': 'Nouveautés',
    'nav.fullEdition': 'Édition complète',
    'common.menu': 'Menu',
    'common.closeMenu': 'Fermer le menu',
    'common.openMenu': 'Ouvrir le menu',
    'common.search': 'Recherche',
    'common.more': 'Voir plus +',
    'common.loginJoin': 'Connexion / Inscription',
    'common.language': 'Langue',
    'common.themeLight': 'Mode clair',
    'common.themeDark': 'Mode sombre',
    'common.displayAdult': 'Afficher les titres adultes',
    'common.showAdult': 'Afficher les titres adultes',
    'common.hideAdult': 'Masquer les titres adultes',
    'common.checkIn': 'Présence',
    'common.comingSoonShortAnime': 'Les anime courts arrivent bientôt.',
    'recent.title': 'Vus récemment',
    'recent.empty': 'Aucun titre vu récemment.',
    'recent.episode': 'Lu jusqu’à l’épisode {episode}',
    'home.latest': 'Nouveautés',
    'home.recentWebtoons': 'Webtoons vus récemment',
    'home.noRecentWebtoons': 'Aucun webtoon vu récemment.',
    'home.recommendReady': 'La recommandation du jour arrive bientôt.',
    'home.recommendSub': 'De nouvelles histoires chaque jour sur ARATA COMICS.',
    'novel.founder': 'Offre membre fondateur ARATA',
    'novel.priceLine': 'Premier mois 990 KRW | Annuel 2 800 KRW/mois',
    'novel.priceSub': 'Le mensuel est à 3 400 KRW. Profitez de tous les contenus à petit prix.',
    'novel.start': 'Commencer',
    'novel.popular': 'Romans populaires',
    'novel.popularSub': 'Découvrez des romans de genres variés, mis à jour chaque jour.',
    'novel.searchPlaceholder': 'Rechercher par titre',
    'category.all': 'Tous',
    'category.fantasy': 'Fantasy',
    'category.martial': 'Arts martiaux',
    'category.romance': 'Romance',
    'category.modern': 'Moderne',
    'category.lightNovel': 'Light novel',
    'category.realtime': 'Temps réel',
    'category.action': 'Action',
    'category.drama': 'Drame',
    'category.school': 'École',
    'category.comedy': 'Comédie',
    'category.thriller': 'Thriller',
    'category.sports': 'Sport',
    'category.daily': 'Tranche de vie',
    'option.freeAll': 'Gratuit',
    'option.firstFree': 'Épisode 1 gratuit',
    'option.webtoon': 'Webtoon',
    'option.comics': 'Comics',
    'option.color': 'Couleur',
    'option.blackWhite': 'Noir et blanc',
    'option.male': 'Public masculin',
    'option.female': 'Public féminin',
    'list.searchPlaceholder': 'Rechercher par titre, créateur ou tag',
    'list.dateSort': 'Plus récents',
    'list.likes': 'J’aime {count}',
    'list.views': 'Vues {count}',
    'list.defaultSynopsis': 'En cours de publication sur ARATA.',
    'list.noTitle': 'Sans titre',
    'list.empty': 'Aucun titre à afficher.',
    'chat.searchPlaceholder': 'Rechercher personnages, titres, créateurs',
    'chat.event': 'Événement',
    'chat.subscriptionSale': 'Abonnement Chat personnages à -50%',
    'chat.ranking': 'Classement personnages en direct',
    'chat.viewAll': 'Tout voir',
    'chat.home': 'Accueil chat',
    'chat.explore': 'Explorer',
    'chat.myChat': 'Mes chats',
    'chat.favorites': 'Favoris',
    'chat.settings': 'Paramètres',
    'chat.popularCharacters': 'Personnages populaires',
    'chat.newScenario': 'Nouveau scénario',
    'chat.noChatTitles': 'Aucun titre disponible pour le chat.',
    'chat.moreTitles': 'Plus de titres',
    'chat.notice': 'Annonce',
    'chat.openNotice': 'ARATA CHAT est ouvert. Abonnez-vous pour discuter avec tous les personnages.',
    'chat.noResults': 'Aucun résultat.',
  },
};

type LanguageContextValue = {
  locale: Locale;
  setLanguage: (locale: Locale) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

const isLocale = (value: string | null): value is Locale =>
  value === 'ko' || value === 'en' || value === 'ja' || value === 'fr';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>('ko');

  useEffect(() => {
    const saved = localStorage.getItem('arata-locale');
    if (isLocale(saved)) {
      setLocale(saved);
      document.documentElement.lang = saved;
    }
  }, []);

  const value = useMemo<LanguageContextValue>(() => {
    const setLanguage = (nextLocale: Locale) => {
      setLocale(nextLocale);
      localStorage.setItem('arata-locale', nextLocale);
      document.documentElement.lang = nextLocale;
    };

    const t = (key: string, replacements?: Record<string, string | number>) => {
      let text = dictionaries[locale][key] || dictionaries.ko[key] || key;
      if (replacements) {
        Object.entries(replacements).forEach(([name, replacement]) => {
          text = text.replaceAll(`{${name}}`, String(replacement));
        });
      }
      return text;
    };

    return { locale, setLanguage, t };
  }, [locale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }
  return context;
}
