'use client';

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Locale = 'ko' | 'en' | 'ja' | 'fr';

export const LANGUAGES: Array<{ code: Locale; label: string; short: string }> = [
  { code: 'ko', label: '한국어', short: 'KO' },
  { code: 'en', label: 'English', short: 'EN' },
  { code: 'ja', label: '日本語', short: 'JA' },
  { code: 'fr', label: 'Français', short: 'FR' },
];

const dictionaries: Record<Locale, Record<string, string>> = {
  ko: {
    'nav.home': '홈',
    'nav.webtoons': '웹툰',
    'nav.books': '단행본',
    'nav.novels': '웹소설',
    'nav.gallery': '화보',
    'nav.community': '게시판',
    'nav.chat': '캐릭터 채팅',
    'nav.shortAnime': '숏폼 애니',
    'nav.games': '게임',
    'nav.events': '이벤트',
    'nav.attendance': '출석',
    'nav.new': '신작',
    'nav.fullEdition': '완전판',
    'common.menu': '메뉴',
    'common.closeMenu': '메뉴 닫기',
    'common.openMenu': '메뉴 열기',
    'common.search': '검색',
    'common.more': '더보기 +',
    'common.loginJoin': '로그인 / 회원가입',
    'common.logout': '로그아웃',
    'common.myPage': '마이페이지',
    'common.myLibrary': '내 서재',
    'common.loggedInAs': '{name}님 로그인 중',
    'common.language': '언어',
    'common.category': '콘텐츠 카테고리',
    'common.themeLight': '라이트 모드',
    'common.themeDark': '다크 모드',
    'common.displayAdult': '성인 작품 표시',
    'common.showAdult': '성인 작품 표시',
    'common.hideAdult': '성인 작품 숨기기',
    'common.checkIn': '출석 체크',
    'common.comingSoonShortAnime': '숏폼 애니는 준비중입니다.',
    'common.previousBanner': '이전 배너',
    'common.nextBanner': '다음 배너',
    'common.bannerPage': '{index}번째 배너 보기',
    'promo.topAria': '연간 결제 시 월 2,800원 프로모션',
    'promo.topAlt': '연간 결제 시 월 2,800원 웹툰 무제한',
    'promo.closeTop': '최상단 배너 닫기',
    'subscription.founder': 'ARATA 창립회원 모집',
    'subscription.firstMonth': '첫 달',
    'subscription.firstPrice': '990원',
    'subscription.annual': '연간 결제 시',
    'subscription.monthlyPrice': '월 2,800원',
    'subscription.description': '이후 월 3,400원. 다양한 웹툰을 무제한으로 감상하세요.',
    'subscription.start': '지금 시작하기',
    'subscription.fullEdition': 'ARATA 완전판',
    'subscription.appDownload': '앱 다운로드',
    'subscription.appDescription': '광고·검열 없는 19+ 버전 설치',
    'recent.title': '최근 본 작품',
    'recent.empty': '최근 감상한 작품이 없습니다.',
    'recent.episode': '{episode}화까지 감상',
    'recent.continueWatching': '내가 보던 웹툰',
    'recent.progress': '{viewed}/{total}화',
    'home.latest': '요일별 연재',
    'home.recentWebtoons': '최근에 본 작품',
    'home.noRecentWebtoons': '최근 감상한 작품이 없습니다.',
    'home.recommended': '오늘의 추천작',
    'home.recommendReady': '오늘의 추천 웹툰이 준비중입니다.',
    'home.recommendSub': '매일 새로운 재미, ARATA COMICS에서 만나보세요.',
    'novel.founder': 'ARATA 창립회원 모집',
    'novel.priceLine': '첫 달 990원 | 연간 결제 시 월 2,800원',
    'novel.priceSub': '월결제 시 월 3,400원. 부담없는 금액으로 모든 콘텐츠를 즐기세요.',
    'novel.start': '지금 시작하기',
    'novel.popular': '인기 소설',
    'novel.popularSub': '매일 업데이트되는 다양한 장르의 소설을 만나보세요.',
    'novel.searchPlaceholder': '소설명으로 검색',
    'books.title': '단행본',
    'books.description': '완결된 이야기를 한 권으로 만나보세요.',
    'books.empty': '등록된 단행본이 없습니다.',
    'category.all': '전체',
    'category.new': '신작',
    'category.ranking': '랭킹',
    'category.fantasy': '판타지',
    'category.martial': '무협',
    'category.romance': '로맨스',
    'category.modern': '현대물',
    'category.lightNovel': '라이트노벨',
    'category.realtime': '실시간',
    'category.action': '액션',
    'category.drama': '드라마',
    'category.school': '학원',
    'category.comedy': '코미디',
    'category.thriller': '스릴러',
    'category.sports': '스포츠',
    'category.daily': '일상',
    'category.adult': '성인',
    'option.freeAll': '완전무료',
    'option.firstFree': '1화 무료',
    'option.webtoon': '웹툰',
    'option.comics': '단행본',
    'option.color': '컬러만화',
    'option.blackWhite': '흑백만화',
    'option.male': '남성향',
    'option.female': '여성향',
    'list.searchPlaceholder': '작품명, 작가명, 태그로 검색해보세요',
    'list.dateSort': '날짜순',
    'list.likes': '좋아요 {count}',
    'list.views': '조회 {count}',
    'list.defaultSynopsis': 'ARATA에서 연재 중인 웹툰입니다.',
    'list.noTitle': '제목 없음',
    'list.empty': '표시할 작품이 없습니다.',
    'detail.notFound': '웹툰을 찾을 수 없습니다.',
    'detail.back': '뒤로',
    'detail.official': '공식연재',
    'detail.rating': '평점',
    'detail.views': '조회',
    'detail.comments': '댓글',
    'detail.totalEpisodes': '총 화수',
    'detail.episodeCount': '{count}화',
    'detail.progress': '읽기 진행률',
    'detail.firstEpisode': '첫 화 보기',
    'detail.favorite': '찜하기',
    'detail.share': '공유',
    'detail.cheerTitle': '작품 응원',
    'detail.cheerSummary': '{supporters}명이 {coins}코인 응원',
    'detail.cheerEmpty': '첫 응원의 주인공이 되어보세요',
    'detail.cheerAction': '응원하기',
    'detail.hallOfFame': '명예의 전당',
    'detail.coins': '{count}코인',
    'detail.cheerHint': '응원이 많은 작품은 외전·시즌2가 우선 제작됩니다.',
    'detail.synopsis': '작품 소개',
    'detail.defaultSynopsis': 'ARATA에서 연재 중인 웹툰입니다.',
    'detail.allEpisodes': '전체 에피소드',
    'detail.read': '읽음',
    'detail.prologue': '프롤로그',
    'detail.episodeNumber': '{number}화',
    'detail.similar': '이 작품과 비슷한 인기작품',
    'detail.noSimilar': '추천 작품이 없습니다.',
    'detail.recommended': '추천 작품',
    'chat.searchPlaceholder': '캐릭터, 작품, 작가 검색',
    'chat.event': '이벤트',
    'chat.subscriptionSale': '아라챗 정액제 50% 할인',
    'chat.ranking': '실시간 캐릭터 랭킹',
    'chat.viewAll': '전체보기',
    'chat.home': '채팅 홈',
    'chat.explore': '탐색',
    'chat.myChat': '내 채팅',
    'chat.favorites': '즐겨찾기',
    'chat.settings': '설정',
    'chat.popularCharacters': '인기 캐릭터',
    'chat.newScenario': '신규 시나리오',
    'chat.noChatTitles': '채팅 가능한 작품이 없습니다.',
    'chat.moreTitles': '작품 더보기',
    'chat.notice': '공지',
    'chat.openNotice': 'ARATA CHAT 오픈! 구독하면 모든 캐릭터와 무제한 대화',
    'chat.noResults': '검색 결과가 없습니다.',
    'chat.mainCharacter': '{title} 주인공',
    'chat.previousCharacter': '이전 캐릭터',
    'chat.nextCharacter': '다음 캐릭터',
    'chat.characterPage': '{index}번째 캐릭터 보기',
    'search.placeholder': '제목, 작가, 태그로 검색',
    'search.resultsTitle': '“{query}” 검색 결과',
    'search.resultCount': '{count}개의 작품을 찾았습니다',
    'search.novel': '소설',
    'search.noResultsTitle': '검색 결과가 없습니다',
    'search.noResultsDescription': '다른 검색어로 시도해보세요',
    'search.promptTitle': '검색어를 입력해주세요',
    'search.promptDescription': '제목, 작가, 태그로 작품을 찾을 수 있습니다',
  },
  en: {
    'nav.home': 'Home',
    'nav.webtoons': 'Webtoons',
    'nav.books': 'Comics',
    'nav.novels': 'Web Novels',
    'nav.gallery': 'Gallery',
    'nav.community': 'Board',
    'nav.chat': 'Character Chat',
    'nav.shortAnime': 'Short Anime',
    'nav.games': 'Games',
    'nav.events': 'Events',
    'nav.attendance': 'Check-in',
    'nav.new': 'New',
    'nav.fullEdition': 'Full Edition',
    'common.menu': 'Menu',
    'common.closeMenu': 'Close menu',
    'common.openMenu': 'Open menu',
    'common.search': 'Search',
    'common.more': 'More +',
    'common.loginJoin': 'Log in / Sign up',
    'common.logout': 'Log out',
    'common.myPage': 'My page',
    'common.myLibrary': 'My library',
    'common.loggedInAs': 'Signed in as {name}',
    'common.language': 'Language',
    'common.category': 'Content categories',
    'common.themeLight': 'Light mode',
    'common.themeDark': 'Dark mode',
    'common.displayAdult': 'Show adult titles',
    'common.showAdult': 'Show adult titles',
    'common.hideAdult': 'Hide adult titles',
    'common.checkIn': 'Check-in',
    'common.comingSoonShortAnime': 'Short anime is coming soon.',
    'common.previousBanner': 'Previous banner',
    'common.nextBanner': 'Next banner',
    'common.bannerPage': 'View banner {index}',
    'promo.topAria': 'Annual plan promotion: 2,800 KRW per month',
    'promo.topAlt': 'Unlimited webtoons for 2,800 KRW per month with the annual plan',
    'promo.closeTop': 'Close top banner',
    'subscription.founder': 'ARATA Founding Member Offer',
    'subscription.firstMonth': 'First month',
    'subscription.firstPrice': '990 KRW',
    'subscription.annual': 'Annual plan',
    'subscription.monthlyPrice': '2,800 KRW/month',
    'subscription.description': 'Then 3,400 KRW per month. Enjoy unlimited access to a wide range of webtoons.',
    'subscription.start': 'Start now',
    'subscription.fullEdition': 'ARATA Full Edition',
    'subscription.appDownload': 'Download the app',
    'subscription.appDescription': 'Install the ad-free, uncensored 19+ version',
    'recent.title': 'Recently Viewed',
    'recent.empty': 'No recently viewed titles.',
    'recent.episode': 'Read through episode {episode}',
    'recent.continueWatching': 'Continue Reading',
    'recent.progress': '{viewed}/{total} episodes',
    'home.latest': 'Weekly Updates',
    'home.recentWebtoons': 'Recently Viewed',
    'home.noRecentWebtoons': 'No recently viewed titles.',
    'home.recommended': 'Today’s Picks',
    'home.recommendReady': 'Today’s recommendation is coming soon.',
    'home.recommendSub': 'Fresh stories every day on ARATA COMICS.',
    'novel.founder': 'ARATA Founding Member Offer',
    'novel.priceLine': 'First month 990 KRW | Annual plan 2,800 KRW/month',
    'novel.priceSub': 'Monthly plan is 3,400 KRW. Enjoy every title at an easy price.',
    'novel.start': 'Start now',
    'novel.popular': 'Popular Novels',
    'novel.popularSub': 'Meet novels across many genres, updated daily.',
    'novel.searchPlaceholder': 'Search by novel title',
    'books.title': 'Comics',
    'books.description': 'Read complete stories in collected editions.',
    'books.empty': 'No comics are available.',
    'category.all': 'All',
    'category.new': 'New',
    'category.ranking': 'Ranking',
    'category.fantasy': 'Fantasy',
    'category.martial': 'Martial Arts',
    'category.romance': 'Romance',
    'category.modern': 'Modern',
    'category.lightNovel': 'Light Novel',
    'category.realtime': 'Real-time',
    'category.action': 'Action',
    'category.drama': 'Drama',
    'category.school': 'School',
    'category.comedy': 'Comedy',
    'category.thriller': 'Thriller',
    'category.sports': 'Sports',
    'category.daily': 'Slice of Life',
    'category.adult': 'Adult',
    'option.freeAll': 'Free',
    'option.firstFree': 'Episode 1 Free',
    'option.webtoon': 'Webtoon',
    'option.comics': 'Comics',
    'option.color': 'Full Color',
    'option.blackWhite': 'Black & White',
    'option.male': 'For Men',
    'option.female': 'For Women',
    'list.searchPlaceholder': 'Search by title, creator, or tag',
    'list.dateSort': 'Newest',
    'list.likes': 'Likes {count}',
    'list.views': 'Views {count}',
    'list.defaultSynopsis': 'Now serializing on ARATA.',
    'list.noTitle': 'Untitled',
    'list.empty': 'No titles to show.',
    'detail.notFound': 'Webtoon not found.',
    'detail.back': 'Back',
    'detail.official': 'Official',
    'detail.rating': 'Rating',
    'detail.views': 'Views',
    'detail.comments': 'Comments',
    'detail.totalEpisodes': 'Episodes',
    'detail.episodeCount': '{count} episodes',
    'detail.progress': 'Reading progress',
    'detail.firstEpisode': 'Read first episode',
    'detail.favorite': 'Favorite',
    'detail.share': 'Share',
    'detail.cheerTitle': 'Support this title',
    'detail.cheerSummary': '{supporters} supporters · {coins} coins',
    'detail.cheerEmpty': 'Be the first supporter',
    'detail.cheerAction': 'Send support',
    'detail.hallOfFame': 'Hall of Fame',
    'detail.coins': '{count} coins',
    'detail.cheerHint': 'Popular support helps prioritize side stories and new seasons.',
    'detail.synopsis': 'Synopsis',
    'detail.defaultSynopsis': 'Now serializing on ARATA.',
    'detail.allEpisodes': 'All episodes',
    'detail.read': 'Read',
    'detail.prologue': 'Prologue',
    'detail.episodeNumber': 'Episode {number}',
    'detail.similar': 'Similar popular titles',
    'detail.noSimilar': 'No recommendations available.',
    'detail.recommended': 'Recommended title',
    'chat.searchPlaceholder': 'Search characters, titles, creators',
    'chat.event': 'Event',
    'chat.subscriptionSale': 'Character Chat plan 50% off',
    'chat.ranking': 'Live Character Ranking',
    'chat.viewAll': 'View all',
    'chat.home': 'Chat Home',
    'chat.explore': 'Explore',
    'chat.myChat': 'My Chats',
    'chat.favorites': 'Favorites',
    'chat.settings': 'Settings',
    'chat.popularCharacters': 'Popular Characters',
    'chat.newScenario': 'New Scenario',
    'chat.noChatTitles': 'No titles available for chat.',
    'chat.moreTitles': 'More titles',
    'chat.notice': 'Notice',
    'chat.openNotice': 'ARATA CHAT is open. Subscribe to chat with every character.',
    'chat.noResults': 'No results found.',
    'chat.mainCharacter': 'Main character of {title}',
    'chat.previousCharacter': 'Previous character',
    'chat.nextCharacter': 'Next character',
    'chat.characterPage': 'View character {index}',
    'search.placeholder': 'Search by title, creator, or tag',
    'search.resultsTitle': 'Results for “{query}”',
    'search.resultCount': '{count} titles found',
    'search.novel': 'Novel',
    'search.noResultsTitle': 'No results found',
    'search.noResultsDescription': 'Try a different search term',
    'search.promptTitle': 'Enter a search term',
    'search.promptDescription': 'Search by title, creator, or tag',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.webtoons': 'ウェブトゥーン',
    'nav.books': '単行本',
    'nav.novels': 'ウェブ小説',
    'nav.gallery': 'ギャラリー',
    'nav.community': '掲示板',
    'nav.chat': 'キャラチャット',
    'nav.shortAnime': 'ショートアニメ',
    'nav.games': 'ゲーム',
    'nav.events': 'イベント',
    'nav.attendance': '出席',
    'nav.new': '新作',
    'nav.fullEdition': '完全版',
    'common.menu': 'メニュー',
    'common.closeMenu': 'メニューを閉じる',
    'common.openMenu': 'メニューを開く',
    'common.search': '検索',
    'common.more': 'もっと見る +',
    'common.loginJoin': 'ログイン / 会員登録',
    'common.logout': 'ログアウト',
    'common.myPage': 'マイページ',
    'common.myLibrary': 'マイライブラリ',
    'common.loggedInAs': '{name}さんでログイン中',
    'common.language': '言語',
    'common.category': 'コンテンツカテゴリー',
    'common.themeLight': 'ライトモード',
    'common.themeDark': 'ダークモード',
    'common.displayAdult': '成人向け作品を表示',
    'common.showAdult': '成人向け作品を表示',
    'common.hideAdult': '成人向け作品を非表示',
    'common.checkIn': '出席チェック',
    'common.comingSoonShortAnime': 'ショートアニメは準備中です。',
    'common.previousBanner': '前のバナー',
    'common.nextBanner': '次のバナー',
    'common.bannerPage': '{index}番目のバナーを表示',
    'promo.topAria': '年間プラン月額2,800ウォンのプロモーション',
    'promo.topAlt': '年間プランなら月額2,800ウォンでウェブトゥーン読み放題',
    'promo.closeTop': '上部バナーを閉じる',
    'subscription.founder': 'ARATA創立会員募集',
    'subscription.firstMonth': '初月',
    'subscription.firstPrice': '990ウォン',
    'subscription.annual': '年間決済で',
    'subscription.monthlyPrice': '月2,800ウォン',
    'subscription.description': '以後月3,400ウォン。多彩なウェブトゥーンを読み放題で楽しめます。',
    'subscription.start': '今すぐ始める',
    'subscription.fullEdition': 'ARATA完全版',
    'subscription.appDownload': 'アプリをダウンロード',
    'subscription.appDescription': '広告・検閲なしの19+版をインストール',
    'recent.title': '最近見た作品',
    'recent.empty': '最近見た作品はありません。',
    'recent.episode': '{episode}話まで閲覧',
    'recent.continueWatching': '続きから読む',
    'recent.progress': '{viewed}/{total}話',
    'home.latest': '曜日別連載',
    'home.recentWebtoons': '最近見た作品',
    'home.noRecentWebtoons': '最近見た作品はありません。',
    'home.recommended': '今日のおすすめ',
    'home.recommendReady': '今日のおすすめは準備中です。',
    'home.recommendSub': '毎日新しい楽しさをARATA COMICSで。',
    'novel.founder': 'ARATA創立会員募集',
    'novel.priceLine': '初月990ウォン | 年間決済で月2,800ウォン',
    'novel.priceSub': '月額は3,400ウォン。手軽な価格で全コンテンツを楽しめます。',
    'novel.start': '今すぐ始める',
    'novel.popular': '人気小説',
    'novel.popularSub': '毎日更新される多彩なジャンルの小説をお楽しみください。',
    'novel.searchPlaceholder': '小説名で検索',
    'books.title': '単行本',
    'books.description': '完結した物語を一冊でお楽しみください。',
    'books.empty': '単行本はまだありません。',
    'category.all': 'すべて',
    'category.new': '新作',
    'category.ranking': 'ランキング',
    'category.fantasy': 'ファンタジー',
    'category.martial': '武侠',
    'category.romance': 'ロマンス',
    'category.modern': '現代',
    'category.lightNovel': 'ライトノベル',
    'category.realtime': 'リアルタイム',
    'category.action': 'アクション',
    'category.drama': 'ドラマ',
    'category.school': '学園',
    'category.comedy': 'コメディ',
    'category.thriller': 'スリラー',
    'category.sports': 'スポーツ',
    'category.daily': '日常',
    'category.adult': '成人',
    'option.freeAll': '完全無料',
    'option.firstFree': '1話無料',
    'option.webtoon': 'ウェブトゥーン',
    'option.comics': '単行本',
    'option.color': 'カラー漫画',
    'option.blackWhite': '白黒漫画',
    'option.male': '男性向け',
    'option.female': '女性向け',
    'list.searchPlaceholder': '作品名、作者名、タグで検索',
    'list.dateSort': '新着順',
    'list.likes': 'いいね {count}',
    'list.views': '閲覧 {count}',
    'list.defaultSynopsis': 'ARATAで連載中のウェブトゥーンです。',
    'list.noTitle': 'タイトルなし',
    'list.empty': '表示できる作品がありません。',
    'detail.notFound': 'ウェブトゥーンが見つかりません。',
    'detail.back': '戻る',
    'detail.official': '公式連載',
    'detail.rating': '評価',
    'detail.views': '閲覧',
    'detail.comments': 'コメント',
    'detail.totalEpisodes': '総話数',
    'detail.episodeCount': '全{count}話',
    'detail.progress': '閲覧進捗',
    'detail.firstEpisode': '第1話を読む',
    'detail.favorite': 'お気に入り',
    'detail.share': '共有',
    'detail.cheerTitle': '作品を応援',
    'detail.cheerSummary': '{supporters}人が{coins}コインで応援',
    'detail.cheerEmpty': '最初の応援者になりましょう',
    'detail.cheerAction': '応援する',
    'detail.hallOfFame': '殿堂入り',
    'detail.coins': '{count}コイン',
    'detail.cheerHint': '応援の多い作品は外伝や新シーズンが優先制作されます。',
    'detail.synopsis': '作品紹介',
    'detail.defaultSynopsis': 'ARATAで連載中のウェブトゥーンです。',
    'detail.allEpisodes': '全エピソード',
    'detail.read': '既読',
    'detail.prologue': 'プロローグ',
    'detail.episodeNumber': '第{number}話',
    'detail.similar': 'この作品に似た人気作品',
    'detail.noSimilar': 'おすすめ作品はありません。',
    'detail.recommended': 'おすすめ作品',
    'chat.searchPlaceholder': 'キャラクター、作品、作者を検索',
    'chat.event': 'イベント',
    'chat.subscriptionSale': 'キャラクターチャット定額制50%割引',
    'chat.ranking': 'リアルタイムキャラクターランキング',
    'chat.viewAll': 'すべて見る',
    'chat.home': 'チャットホーム',
    'chat.explore': '探索',
    'chat.myChat': 'マイチャット',
    'chat.favorites': 'お気に入り',
    'chat.settings': '設定',
    'chat.popularCharacters': '人気キャラクター',
    'chat.newScenario': '新規シナリオ',
    'chat.noChatTitles': 'チャット可能な作品はありません。',
    'chat.moreTitles': '作品をもっと見る',
    'chat.notice': 'お知らせ',
    'chat.openNotice': 'ARATA CHAT公開。登録すると全キャラクターとチャットできます。',
    'chat.noResults': '検索結果がありません。',
    'chat.mainCharacter': '「{title}」の主人公',
    'chat.previousCharacter': '前のキャラクター',
    'chat.nextCharacter': '次のキャラクター',
    'chat.characterPage': '{index}番目のキャラクターを表示',
    'search.placeholder': 'タイトル、作者、タグで検索',
    'search.resultsTitle': '「{query}」の検索結果',
    'search.resultCount': '{count}作品が見つかりました',
    'search.novel': '小説',
    'search.noResultsTitle': '検索結果がありません',
    'search.noResultsDescription': '別のキーワードをお試しください',
    'search.promptTitle': '検索キーワードを入力してください',
    'search.promptDescription': 'タイトル、作者、タグから作品を検索できます',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.webtoons': 'Webtoons',
    'nav.books': 'Bandes dessinées',
    'nav.novels': 'Romans web',
    'nav.gallery': 'Galerie',
    'nav.community': 'Forum',
    'nav.chat': 'Chat personnages',
    'nav.shortAnime': 'Anime court',
    'nav.games': 'Jeux',
    'nav.events': 'Événements',
    'nav.attendance': 'Présence',
    'nav.new': 'Nouveautés',
    'nav.fullEdition': 'Édition complète',
    'common.menu': 'Menu',
    'common.closeMenu': 'Fermer le menu',
    'common.openMenu': 'Ouvrir le menu',
    'common.search': 'Recherche',
    'common.more': 'Voir plus +',
    'common.loginJoin': 'Connexion / Inscription',
    'common.logout': 'Déconnexion',
    'common.myPage': 'Mon compte',
    'common.myLibrary': 'Ma bibliothèque',
    'common.loggedInAs': 'Connecté : {name}',
    'common.language': 'Langue',
    'common.category': 'Catégories de contenu',
    'common.themeLight': 'Mode clair',
    'common.themeDark': 'Mode sombre',
    'common.displayAdult': 'Afficher les titres adultes',
    'common.showAdult': 'Afficher les titres adultes',
    'common.hideAdult': 'Masquer les titres adultes',
    'common.checkIn': 'Présence',
    'common.comingSoonShortAnime': 'Les anime courts arrivent bientôt.',
    'common.previousBanner': 'Bannière précédente',
    'common.nextBanner': 'Bannière suivante',
    'common.bannerPage': 'Afficher la bannière {index}',
    'promo.topAria': 'Offre annuelle à 2 800 KRW par mois',
    'promo.topAlt': 'Webtoons illimités à 2 800 KRW par mois avec le forfait annuel',
    'promo.closeTop': 'Fermer la bannière supérieure',
    'subscription.founder': 'Offre membre fondateur ARATA',
    'subscription.firstMonth': 'Premier mois',
    'subscription.firstPrice': '990 KRW',
    'subscription.annual': 'Forfait annuel',
    'subscription.monthlyPrice': '2 800 KRW/mois',
    'subscription.description': 'Puis 3 400 KRW par mois. Profitez d’un accès illimité à de nombreux webtoons.',
    'subscription.start': 'Commencer',
    'subscription.fullEdition': 'Édition complète ARATA',
    'subscription.appDownload': 'Télécharger l’application',
    'subscription.appDescription': 'Installez la version 19+ sans publicité ni censure',
    'recent.title': 'Vus récemment',
    'recent.empty': 'Aucun titre vu récemment.',
    'recent.episode': 'Lu jusqu’à l’épisode {episode}',
    'recent.continueWatching': 'Continuer la lecture',
    'recent.progress': '{viewed}/{total} épisodes',
    'home.latest': 'Parutions par jour',
    'home.recentWebtoons': 'Vus récemment',
    'home.noRecentWebtoons': 'Aucune œuvre vue récemment.',
    'home.recommended': 'Sélection du jour',
    'home.recommendReady': 'La recommandation du jour arrive bientôt.',
    'home.recommendSub': 'De nouvelles histoires chaque jour sur ARATA COMICS.',
    'novel.founder': 'Offre membre fondateur ARATA',
    'novel.priceLine': 'Premier mois 990 KRW | Annuel 2 800 KRW/mois',
    'novel.priceSub': 'Le mensuel est à 3 400 KRW. Profitez de tous les contenus à petit prix.',
    'novel.start': 'Commencer',
    'novel.popular': 'Romans populaires',
    'novel.popularSub': 'Découvrez des romans de genres variés, mis à jour chaque jour.',
    'novel.searchPlaceholder': 'Rechercher par titre',
    'books.title': 'Bandes dessinées',
    'books.description': 'Retrouvez des histoires complètes en volumes.',
    'books.empty': 'Aucune bande dessinée disponible.',
    'category.all': 'Tous',
    'category.new': 'Nouveautés',
    'category.ranking': 'Classement',
    'category.fantasy': 'Fantasy',
    'category.martial': 'Arts martiaux',
    'category.romance': 'Romance',
    'category.modern': 'Moderne',
    'category.lightNovel': 'Light novel',
    'category.realtime': 'Temps réel',
    'category.action': 'Action',
    'category.drama': 'Drame',
    'category.school': 'École',
    'category.comedy': 'Comédie',
    'category.thriller': 'Thriller',
    'category.sports': 'Sport',
    'category.daily': 'Tranche de vie',
    'category.adult': 'Adulte',
    'option.freeAll': 'Gratuit',
    'option.firstFree': 'Épisode 1 gratuit',
    'option.webtoon': 'Webtoon',
    'option.comics': 'Comics',
    'option.color': 'Couleur',
    'option.blackWhite': 'Noir et blanc',
    'option.male': 'Public masculin',
    'option.female': 'Public féminin',
    'list.searchPlaceholder': 'Rechercher par titre, créateur ou tag',
    'list.dateSort': 'Plus récents',
    'list.likes': 'J’aime {count}',
    'list.views': 'Vues {count}',
    'list.defaultSynopsis': 'En cours de publication sur ARATA.',
    'list.noTitle': 'Sans titre',
    'list.empty': 'Aucun titre à afficher.',
    'detail.notFound': 'Webtoon introuvable.',
    'detail.back': 'Retour',
    'detail.official': 'Officiel',
    'detail.rating': 'Note',
    'detail.views': 'Vues',
    'detail.comments': 'Commentaires',
    'detail.totalEpisodes': 'Épisodes',
    'detail.episodeCount': '{count} épisodes',
    'detail.progress': 'Progression',
    'detail.firstEpisode': 'Lire le premier épisode',
    'detail.favorite': 'Favori',
    'detail.share': 'Partager',
    'detail.cheerTitle': 'Soutenir cette œuvre',
    'detail.cheerSummary': '{supporters} soutiens · {coins} pièces',
    'detail.cheerEmpty': 'Soyez la première personne à soutenir cette œuvre',
    'detail.cheerAction': 'Soutenir',
    'detail.hallOfFame': 'Temple de la renommée',
    'detail.coins': '{count} pièces',
    'detail.cheerHint': 'Les œuvres les plus soutenues sont prioritaires pour les hors-séries et nouvelles saisons.',
    'detail.synopsis': 'Synopsis',
    'detail.defaultSynopsis': 'En cours de publication sur ARATA.',
    'detail.allEpisodes': 'Tous les épisodes',
    'detail.read': 'Lu',
    'detail.prologue': 'Prologue',
    'detail.episodeNumber': 'Épisode {number}',
    'detail.similar': 'Œuvres populaires similaires',
    'detail.noSimilar': 'Aucune recommandation disponible.',
    'detail.recommended': 'Œuvre recommandée',
    'chat.searchPlaceholder': 'Rechercher personnages, titres, créateurs',
    'chat.event': 'Événement',
    'chat.subscriptionSale': 'Abonnement Chat personnages à -50%',
    'chat.ranking': 'Classement personnages en direct',
    'chat.viewAll': 'Tout voir',
    'chat.home': 'Accueil chat',
    'chat.explore': 'Explorer',
    'chat.myChat': 'Mes chats',
    'chat.favorites': 'Favoris',
    'chat.settings': 'Paramètres',
    'chat.popularCharacters': 'Personnages populaires',
    'chat.newScenario': 'Nouveau scénario',
    'chat.noChatTitles': 'Aucun titre disponible pour le chat.',
    'chat.moreTitles': 'Plus de titres',
    'chat.notice': 'Annonce',
    'chat.openNotice': 'ARATA CHAT est ouvert. Abonnez-vous pour discuter avec tous les personnages.',
    'chat.noResults': 'Aucun résultat.',
    'chat.mainCharacter': 'Personnage principal de {title}',
    'chat.previousCharacter': 'Personnage précédent',
    'chat.nextCharacter': 'Personnage suivant',
    'chat.characterPage': 'Afficher le personnage {index}',
    'search.placeholder': 'Rechercher par titre, créateur ou tag',
    'search.resultsTitle': 'Résultats pour « {query} »',
    'search.resultCount': '{count} œuvres trouvées',
    'search.novel': 'Roman',
    'search.noResultsTitle': 'Aucun résultat',
    'search.noResultsDescription': 'Essayez un autre terme de recherche',
    'search.promptTitle': 'Saisissez un terme de recherche',
    'search.promptDescription': 'Recherchez par titre, créateur ou tag',
  },
};

type LanguageContextValue = {
  locale: Locale;
  setLanguage: (locale: Locale) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

const isLocale = (value: string | null): value is Locale =>
  value === 'ko' || value === 'en' || value === 'ja' || value === 'fr';

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>('ko');

  useEffect(() => {
    const saved = localStorage.getItem('arata-locale');
    if (isLocale(saved)) {
      setLocale(saved);
      document.documentElement.lang = saved;
    }
  }, []);

  const value = useMemo<LanguageContextValue>(() => {
    const setLanguage = (nextLocale: Locale) => {
      setLocale(nextLocale);
      localStorage.setItem('arata-locale', nextLocale);
      document.documentElement.lang = nextLocale;
    };

    const t = (key: string, replacements?: Record<string, string | number>) => {
      let text = dictionaries[locale][key] || dictionaries.ko[key] || key;
      if (replacements) {
        Object.entries(replacements).forEach(([name, replacement]) => {
          text = text.replaceAll(`{${name}}`, String(replacement));
        });
      }
      return text;
    };

    return { locale, setLanguage, t };
  }, [locale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }
  return context;
}
